name: ParallelizedIterators
version: "2021.12-01"
license: "GPL-2.0-or-later"
date: 2021-12-24
description: |
    Parallely evaluate recursive iterators

authors:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/
    - name: Reimer Behrends
      url: https://github.com/rbehrends
    - name: Lukas Kühne
      url: https://github.com/lukaskuehne

maintainers:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/
    - name: Reimer Behrends
      url: https://github.com/rbehrends
    - name: Lukas Kühne
      url: https://github.com/lukaskuehne

GAP: ">= 4.9.1"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "IO"
      version: ">= 4.5.1"
      url: "https://gap-packages.github.io/io"
    - name: "ToolsForHomalg"
      version: ">= 2018.12.01"
      url: "https://homalg-project.github.io/pkg/ToolsForHomalg"

www: https://homalg-project.github.io/pkg/ParallelizedIterators
readme: README.md
packageinfo: https://homalg-project.github.io/ParallelizedIterators/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/ParallelizedIterators/releases/download/v2021.12-01/ParallelizedIterators-2021.12-01.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/ParallelizedIterators/releases/download/v2021.12-01/ParallelizedIterators-2021.12-01.zip

pdf: https://github.com/homalg-project/ParallelizedIterators/releases/download/v2021.12-01/ParallelizedIterators-2021.12-01.pdf

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    recursive iterators, parallel evaluation.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>BBK21</span>]   <b class='BibAuthor'>Barakat, M., Behrends, R. and Kühne, L.</b>,
     <i class='BibTitle'>ParallelizedIterators, Parallely evaluate recursive iterators,
             Version 2021.12-01</i>
     (<span class='BibYear'>2021</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://homalg-project.github.io/pkg/ParallelizedIterators">https://homalg-project.github.io/pkg/ParallelizedIterators</a></span>.
    </p>
    

bibtex: |
    @misc{ ParallelizedIterators2021.12-01,
      author =           {Barakat, M. and Behrends, R. and K{\"u}hne, L.},
      title =            {{ParallelizedIterators},  Parallely evaluate recursive
                          iterators, {V}ersion 2021.12-01},
      month =            {Dec},
      year =             {2021},
      note =             {GAP package},
      howpublished =     {\href
                          {https://homalg-project.github.io/pkg/ParallelizedIterators}
                          {\texttt{https://homalg-project.github.io/}\discretionary
                          {}{}{}\texttt{pkg/}\discretionary
                          {}{}{}\texttt{ParallelizedIterators}}},
      keywords =         {recursive iterators, parallel evaluation},
      printedkey =       {BBK21}
    }

