name: ParallelizedIterators
version: 2019.06.06
date: 06/06/2019
description: Parallely evaluate recursive iterators

authors:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io
    - name: Reimer Behrends
      url: https://github.com/rbehrends
    - name: Lukas Kühne
      url: https://github.com/lukaskuehne

maintainers:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io
    - name: Reimer Behrends
      url: https://github.com/rbehrends
    - name: Lukas Kühne
      url: https://github.com/lukaskuehne

GAP: ">= 4.9.1"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "IO"
      version: ">= 4.5.1"
      url: "https://gap-packages.github.io/io"
    - name: "ToolsForHomalg"
      version: ">= 2018.12.01"
      url: "https://homalg-project.github.io/homalg_project/ToolsForHomalg/"

www: https://homalg-project.github.io/ParallelizedIterators
readme: README.md
packageinfo: https://homalg-project.github.io/ParallelizedIterators/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/ParallelizedIterators/releases/download/v2019.06.06/ParallelizedIterators-2019.06.06.tar.gz

abstract: 

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
